AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template for PostgreSQL RDS instance  
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: choose VpcId of your existing Virtual Private Cloud(VPC)
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: 'The list of SubnetIds,for at least two Availability Zones in the region'
  DBIdentifier:
    Type: String
    Description: The identifier of this mysql database
  MyDBName:
    Default: PGDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  EngineVersion:
    Description: Engine Version
    Type: String
    Default: 9.3.12
    AllowedValues:
      - 9.3.12
      - 9.3.14
      - 9.3.16
      - 9.3.17
      - 9.3.19
      - 9.3.20
      - 9.3.22
      - 9.3.23
      - 9.3.24
      - 9.3.25
  DBUser:
    Description: The database admin account username
    Default: pgadmin
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  MyDBInstanceClass:
    Description: RDS instance type
    Type: String
    Default: db.t2.micro
    ConstraintDescription: must select a valid database instance type.
    AllowedValues:
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
      - db.t3.2xlarge 	
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
  MultiAZDatabase:
    Default: 'false'
    Description: Create a multi-AZ RDS database instance
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    ConstraintDescription: must be either true or false.
  CIDRIP:
    Description: The IP address range that can be used to connect to Database
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
Resources:
  MyDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds: !Ref Subnets
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow access to the mysql from the Web Server
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: !Ref CIDRIP
  MyDataBase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      AutoMinorVersionUpgrade: 'false'
      VPCSecurityGroups:
        - !Ref SecurityGroup
      DBName: !Ref MyDBName
      DBInstanceClass: !Ref MyDBInstanceClass
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      Engine: postgres
      EngineVersion: !Ref EngineVersion
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: !Ref MultiAZDatabase
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Ref DBIdentifier
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value: !Join 
      - ''
      - - 'jdbc:postgresql://'
        - !GetAtt 
          - MyDataBase
          - Endpoint.Address
        - ':'
        - !GetAtt 
          - MyDataBase
          - Endpoint.Port
        - /
        - !Ref MyDBName
  DBAddress:
    Description: address of database endpoint
    Value: !GetAtt 
      - MyDataBase
      - Endpoint.Address
  DBPort:
    Description: database endpoint port
    Value: !GetAtt 
      - MyDataBase
      - Endpoint.Port
